### ISSUE TITLE
Correct use of AESHash

### ISSUE THREAD

**Issue by ashish-goswami** [coocood/badger#103]
Hey @coocood ,

I saw you are using AES Hash(from go runtime package) in bloom filters. One thing I observed is that, it returns different hash for the same key if I run it multiple times.
Bloom filters are persisted on the disk. Hence I think bloom filter might return incorrect result for some key presence if I reopen already existing Badger directory.

Did you also observe this or am I missing something?

Here is the simple test, I wrote to reproduce this(in github.com/coocood/rtutil)

```go
func TestOne(t *testing.T) {
        key := []byte("abc")
        l := AESHash(key)
        fmt.Println(l)
}
```

**Comment by coocood** [comment]
@ashish-goswami 

Good catch, thank you!
I didn't update the dependency version of `bbloom` in badger, so I didn't notice this bug.
I will revert the latest commit on `bbloom`.

**Comment by coocood** [comment]
I found that gofarm is much faster than sipHash, so I replaced it again to `gofarm` 

https://github.com/coocood/bbloom/commit/107615371da215219ba142a95cb3f309df411fc5

**Comment by ashish-goswami** [comment]
Great! Thanks for the quick response.
